# Generated by Django 3.0.7 on 2020-08-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20200814_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users1',
            new_name='User',
        ),
    ]
